### ISSUE TITLE
Explainable AI Demo/Brownbag (XAI)

### ISSUE THREAD

**Issue by nackerson-ventera** [nackerson-ventera/HAIV-POCs#9]
Explainable AI - Practice to understanding and explaining Machine Learning Model predictions.

### Prototype motivation
To demonstrate interpretable models and XAI to Ventera staff via brownbag and to have the processes in place for future products

### Problem definition

- [x] specific output to predict
- [x] input data (estimated number of rows)
- [x] location (where to access??)
- [x] relevant factors for predicting our output
- [x] number of training examples

### Performance measurement
- [x] benchmark to compare against?
- [x] our process to measure accuracy

### Roadmap/timeline

- [x] deadline  2/9? PoC date 2/16?
- [x] cadence (demos 1/26, 2/2)
- [x] reviews/dry runs (1/25, 2/1, 2/8)

 

Aha! Link: https://ventera-corporation.aha.io/features/NOBLE-5
